PREFIX = /usr/local
ARHCH = h8300-elf
BINDIR = $(PREFIX)/bin
ADDNAME = $(ARHCH)-

# root@3056ea74c634:/# /usr/local/bin/h8300-elf-gcc --version
# h8300-elf-gcc (GCC) 3.4.6
AR = $(BINDIR)/$(ARHCH)-ar
AS = $(BINDIR)/$(ARHCH)-as
GCC = $(BINDIR)/$(ARHCH)-gcc
LD = $(BINDIR)/$(ARHCH)-ld
NM = $(BINDIR)/$(ARHCH)-nm
OBJCOPY = $(BINDIR)/$(ARHCH)-objcopy
OBJDUMP = $(BINDIR)/$(ARHCH)-objdump
RANLIB = $(BINDIR)/$(ARHCH)-ranlib
STRIP = $(BINDIR)/$(ARHCH)-strip

H8WRITE = ../tools/h8write/h8write
